spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/hrms
    username: root
    password: test

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: praveenagrawal4073@gmail.com
    password: mkrp fqll cnga mqvj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


#logging:
#  level:
#    root: INFO
#    com.hrms: DEBUG
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
#  file:
##    name: logs/app.log
