spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/hrms1
    username: root
    password: test123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
